name: Build and Deploy 🚀

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
          
      - name: Restore
        run: dotnet restore ./Starter/Starter.sln
        
      - name: Build
        run: dotnet build ./Starter/Starter.sln --configuration Release --no-restore
